exports.apiResponse = {
    // Common
    SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
    SUCCESS: "SUCCESS",
    CREATED_SUCCESS: "CREATED_SUCCESS",
    UPDATED_SUCCESS: "UPDATED_SUCCESS",
    DELETED_SUCCESS: "DELETED_SUCCESS",
    NO_DATA_FOUND: "NO_DATA_FOUND",
    DATA_FETCHED_SUCCESSFULLY: "DATA_FETCHED_SUCCESSFULLY",
    INVALID_ID: "INVALID_ID",
    INVALID_PARAMETERS: "INVALID_PARAMETERS",

    // Auth/Middleware messages
    FORMAT_BEARER_TOKEN: "FORMAT_BEARER_TOKEN",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    INVALID_TOKEN: "INVALID_TOKEN",
    TOKEN_MISMATCH: "TOKEN_MISMATCH",
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
    ADMIN_ACCESS_REQUIRED: "ADMIN_ACCESS_REQUIRED",

    // Admin Login
    ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
    ADMIN_LOGIN_FAILED: "ADMIN_LOGIN_FAILED",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    
    // Gallery related messages
    GALLERY_CREATED_SUCCESS: "GALLERY_CREATED_SUCCESS",
    GALLERY_UPDATED_SUCCESS: "GALLERY_UPDATED_SUCCESS",
    GALLERY_DELETED_SUCCESS: "GALLERY_DELETED_SUCCESS",
    GALLERY_FETCHED_SUCCESS: "GALLERY_FETCHED_SUCCESS",
    GALLERIES_FETCHED_SUCCESS: "GALLERIES_FETCHED_SUCCESS",
    GALLERY_NOT_FOUND: "GALLERY_NOT_FOUND",

    // Photo related messages
    PHOTO_UPLOADED_SUCCESS: "PHOTO_UPLOADED_SUCCESS",
    PHOTO_DELETED_SUCCESS: "PHOTO_DELETED_SUCCESS",
    PHOTO_FETCHED_SUCCESS: "PHOTO_FETCHED_SUCCESS",
    PHOTOS_FETCHED_SUCCESS: "PHOTOS_FETCHED_SUCCESS",
    PHOTO_NOT_FOUND: "PHOTO_NOT_FOUND",
    IMAGE_UPLOAD_FAILED: "IMAGE_UPLOAD_FAILED",

    // Testimonial related messages
    TESTIMONIAL_CREATED_SUCCESS: "TESTIMONIAL_CREATED_SUCCESS",
    TESTIMONIAL_UPDATED_SUCCESS: "TESTIMONIAL_UPDATED_SUCCESS",
    TESTIMONIAL_DELETED_SUCCESS: "TESTIMONIAL_DELETED_SUCCESS",
    TESTIMONIAL_APPROVED_SUCCESS: "TESTIMONIAL_APPROVED_SUCCESS",
    TESTIMONIAL_FETCHED_SUCCESS: "TESTIMONIAL_FETCHED_SUCCESS",
    TESTIMONIALS_FETCHED_SUCCESS: "TESTIMONIALS_FETCHED_SUCCESS",
    TESTIMONIAL_NOT_FOUND: "TESTIMONIAL_NOT_FOUND",

    // Booking related messages
    BOOKING_CREATED_SUCCESS: "BOOKING_CREATED_SUCCESS",
    BOOKING_UPDATED_SUCCESS: "BOOKING_UPDATED_SUCCESS",
    BOOKING_STATUS_UPDATED: "BOOKING_STATUS_UPDATED",
    BOOKING_FETCHED_SUCCESS: "BOOKING_FETCHED_SUCCESS",
    BOOKINGS_FETCHED_SUCCESS: "BOOKINGS_FETCHED_SUCCESS",
    BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",

    // Contact related messages
    CONTACT_MESSAGE_SENT: "CONTACT_MESSAGE_SENT",
    CONTACT_UPDATED_SUCCESS: "CONTACT_UPDATED_SUCCESS",
    CONTACT_FETCHED_SUCCESS: "CONTACT_FETCHED_SUCCESS",
    CONTACTS_FETCHED_SUCCESS: "CONTACTS_FETCHED_SUCCESS",
    CONTACT_NOT_FOUND: "CONTACT_NOT_FOUND",

    // Settings related messages
    SETTINGS_FETCHED_SUCCESS: "SETTINGS_FETCHED_SUCCESS",
    SETTINGS_UPDATED_SUCCESS: "SETTINGS_UPDATED_SUCCESS",
    SETTINGS_NOT_FOUND: "SETTINGS_NOT_FOUND",

    // Validation messages
    VALIDATION_ERROR: "VALIDATION_ERROR",
    REQUIRED_FIELDS_MISSING: "REQUIRED_FIELDS_MISSING",
    INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
    INVALID_PHONE_FORMAT: "INVALID_PHONE_FORMAT",
    INVALID_DATE_FORMAT: "INVALID_DATE_FORMAT",
    INVALID_IMAGE_FORMAT: "INVALID_IMAGE_FORMAT",
};

